### ISSUE TITLE
مشارکت

### ISSUE THREAD

**Issue by Mohammadreza-73** [persian-tools/php-persian-tools#2]
سلام
دیدم که این PHP بنده خدا هنوز همه ابزارهاش تکمیل نشده.
من تازه کارم میتونم مشارکت کنم؟

**Comment by ali-master** [comment]
سلام محمد رضا جان

من یه پیگیری میکنم با بچه ها که دوباره کاری نکنیم روی پیاده سازی و توسعه

**Comment by faridfr** [comment]
@Mohammadreza-73 

<p dir="rtl">
سلام میتونیم یه هماهنگی با هم داشته باشیم
</p>
